In [1]:
#Ques-1
#import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#load the Dataset & head,shape
dc=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data')
dc.head()

B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [3]:
dc.shape

(624, 5)

In [4]:
from sklearn.model_selection import train_test_split as tst
train,test = tst(dc,test_size=0.3)

In [5]:
train_x = train.loc[:,train.columns != 'B']
test_x = test.loc[:,test.columns != 'B']

train_y = train['B']
test_y = test['B']

In [15]:
from sklearn.tree import DecisionTreeClassifier
#model=DTC()
model.fit(train_x,train_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [17]:
pred_y = model.predict(test_x)

In [18]:
finres = pd.DataFrame({'Actual': test_y,'Predicted' : pred_y})
print(finres)

    Actual Predicted
381      R         R
311      B         R
271      R         R
21       R         R
521      R         R
281      B         L
173      R         R
48       R         R
144      R         R
612      L         L
490      L         L
61       R         R
113      R         R
453      L         L
160      R         B
615      L         L
491      L         L
305      L         L
346      R         B
563      B         R
347      R         R
261      R         R
394      R         B
574      L         L
485      L         L
577      L         L
122      R         R
229      L         L
241      R         R
376      L         B
..     ...       ...
474      L         L
47       R         R
14       R         R
340      L         L
556      L         L
212      R         R
325      L         L
303      L         L
440      L         L
395      R         R
592      L         B
426      L         L
26       R         B
242      R         R
313      R         R
607      L   

In [19]:
from sklearn.metrics import confusion_matrix as cm, classification_report as clr
print(cm(test_y,pred_y))
print(clr(test_y,pred_y))

[[ 1  7  4]
 [11 83  0]
 [11  2 69]]
             precision    recall  f1-score   support

          B       0.04      0.08      0.06        12
          L       0.90      0.88      0.89        94
          R       0.95      0.84      0.89        82

avg / total       0.87      0.81      0.84       188



In [17]:
#Accuracy score
from sklearn.metrics import accuracy_score
accuracy_score = accuracy_score(test_y,pred_y)
print("A final Accuracy Score is : {}".format(accuracy_score))


A final Accuracy Score is : 0.824468085106
