In [2]:
#libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
#loading dataset
data = sns.load_dataset('iris')
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
from sklearn.model_selection import train_test_split as tst
train,test=tst(data,test_size=0.15)

In [8]:
train_x = train.loc[:,train.columns  != 'species']
test_x =  test.loc[:,test.columns != 'species']

train_y = train['species']
test_y = test['species']

In [9]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(train_x,train_y)

GaussianNB(priors=None)

In [10]:
pred_y = gnb.predict(test_x)

In [11]:
rslt = pd.DataFrame({'Actual': test_y,'Predicted': pred_y})
print(rslt)

         Actual   Predicted
135   virginica   virginica
123   virginica   virginica
44       setosa      setosa
84   versicolor  versicolor
18       setosa      setosa
83   versicolor  versicolor
99   versicolor  versicolor
111   virginica   virginica
43       setosa      setosa
36       setosa      setosa
33       setosa      setosa
126   virginica   virginica
16       setosa      setosa
12       setosa      setosa
47       setosa      setosa
92   versicolor  versicolor
130   virginica   virginica
73   versicolor  versicolor
40       setosa      setosa
108   virginica   virginica
121   virginica   virginica
17       setosa      setosa
19       setosa      setosa


In [12]:
from sklearn.metrics import confusion_matrix as cm, classification_report as clr
print(cm(test_y,pred_y))
print(clr(test_y,pred_y))

[[11  0  0]
 [ 0  5  0]
 [ 0  0  7]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       1.00      1.00      1.00         5
  virginica       1.00      1.00      1.00         7

avg / total       1.00      1.00      1.00        23



In [13]:
#multinomial
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(train_x,train_y)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [14]:
pred_y = mnb.predict(test_x)

In [16]:
#result = pd.DataFrame({'Actual': test_y,'Predicted': pred_y})
#print(result)